name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print greeting
      run: echo "Hello World!"
    - name: Print goodbye
      run: echo "Done - bye!"
    - name: Print multiple shell commands
      run: |
          echo "First shell command"
          echo "Second shell command"
